/* Code Generated by William Derksen

A not so simple running adder...
I failed to find neither a clean, nor effective way of doing this.

*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>

int limitedScanf(char *in);
int addOverflow(int x, int *y);

int main(){

    /**
    A program that computes a running addition of terminal input numbers and displays the result.
    */
    int add = 0;
    int *addp = &add;
    char in[9];
    int err;
    do{
        // Get error code for having too large a number
        err = limitedScanf(in);

        if (err == 2){
            printf("Unfortunately I can't process anything that large, I am but a feeble code. Try again!\n");
            continue;
        }


        int x = atoi(in);
        if (x == 0){
            printf("You put in something that wasn't a number!  Or a zero maybe... Try again!\n");
            continue;
        }

        if (addOverflow(x, addp) != 0){
            printf("Your numbers are too big and can no longer be added! You probably shouldn't try again...\n");
            continue;
        }

    } while ( err != EOF && err != 3 ); //Look for EOF
}


int limitedScanf(char *in){
    /**
    A function to be certain the number inputed is within the input length.  Correctly clears stdin when there is information to be cleared
    in : The array (pointer) where we save the scanned input.
    */
    int scanret = scanf("%9s",in);
    char c = getchar();
    if (c == EOF){
        return 3; // Code for EOF (while loop EOF checking doesn't work)
    }

    // If the string len is full and the next character wasn't a newline, then our number was too big
    if (strlen(in) == 9 && c != '\n'){ 
        while (getchar() != '\n');
        return 2; // Error code for having too long a number
    }

    // 0 => didn't find a number; -1 => EOF
    return scanret; 
}

int addOverflow(int x, int * y){
    /**
    A function to determine whether the result of addition will overflow before that occurs.
    x : The number to be added
    y : The pointer to the running addition value
    */
    if(x > 0 && *y > 0 && (x > INT_MAX - *y))
        return 1;
    if(x < 0 && *y < 0 && (x < INT_MIN - *y))
        return 1;
    *y += x;
    printf("tot: %i\n\n", *y);
    return 0;
}